version: '3.8'

services:
  # 1. PostgreSQL với PGVector
  postgres-db:
    image: pgvector/pgvector:pg15
    container_name: booking-postgres
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - cab-network
    command: postgres -c "shared_preload_libraries=vector"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 5. Booking Service
  booking-service:
    build:
      context: . # Sửa thành dấu chấm vì đang đứng trong chính thư mục này
      dockerfile: Dockerfile
    container_name: cab-booking-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - KAFKA_URL=kafka:9092
      - POSTGRES_URL=jdbc:postgresql://booking-postgres:5432/booking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - kafka
      - postgres-db
    networks:
      - cab-network

networks:
  cab-network:
    external: true